### ISSUE TITLE
feat(storage): Implement a way to handle persisting <contract Trie<keys, values>>

### ISSUE THREAD

**Issue by antiyro** [madara-alliance/bonsai-trie#18]
### Current behavior:

Currently the Starknet state root is computed using 3 persistent tries:
- **Contract trie**: A contract trie mapping contract addresses to a hashed representation of its storage containing it's storage root. (we store it in a `contract_bonsai_db`)
- **Storage trie**: A storage trie representing the root of a particular contract based on all it's key/value changes along the state (we store it in a `storage_bonsai_db`)
- **Class trie**: A class mapping class hashes to their compiled class hashes (we store it in a `class_bonsai_db`)

For the Contract and Class trie the bonsai lib works correctly.

The problem is regarding the storage trie. With the current lib there is no way to persist storage changes of a specific contract since the key/values associated to it are stored in the `storage_bonsai_db` without any contract identifier to retrieve them.

### Provisory fix

The provisory fix we implemented is that for each Contract were storage changes were detected we retireve all the storage key values associated to store them along with the new changes and recompute the trie in memory. The problem is that it means we need to store the key/values duplicated in our codebase (to persist them with an associated contract) + it is really costly to do so

The goal would be to find an internal solution within the Bonsai-trie lib to this problem.

**Comment by AurelienFT** [comment]
Done in #21
