### ISSUE TITLE
bug(insert): :bug: double insertion results in `BonsaiStorageError`

### ISSUE THREAD

**Issue by Trantorian1** [madara-alliance/bonsai-trie#19]
# Bug Report

**Bonsai-trie version:** 322af3f

**Current behavior:**

Double insertion of the same key into a bonsai db *without calling* `commit` *between insertions* results in [`BonsaiStorageError::Trie("Couldn't fetch node in db")`](https://github.com/keep-starknet-strange/bonsai-trie/blob/322af3f9f0c7ea4eccfca0f351df5fff43009d64/src/trie/merkle_tree.rs#L855).

According to @AurelienFT this could be due to the db trying to access the key to replace it while it hasn't yet been committed to storage.

**Expected behavior:**

Bonsai db should be able to handle double insertions without having to `commit` to storage.

**Steps to reproduce:**

Perform double insertion of the same key into a bonsai db in a single commit.

**Related code:**

The function currently crashing: [`preload_node_subtree`](https://github.com/keep-starknet-strange/bonsai-trie/blob/322af3f9f0c7ea4eccfca0f351df5fff43009d64/src/trie/merkle_tree.rs#L824)

**Comment by AurelienFT** [comment]
Fixed by #20
